export const eventsAndResources = [
    {
      id: 1,
      title: "Kanye West",
      description: "My 🐐. Musical Genius",
      album: "Late Registeration",
      image: "https://upload.wikimedia.org/wikipedia/en/f/f4/Late_registration_cd_cover.jpg",
      streams: "1.59B",
    },
    {
      id: 2,
      title: "C418",
      description: "If you are looking to relax on a rainy day",
      album: "Minecraft - Volume Alpha",
      image: "https://upload.wikimedia.org/wikipedia/en/5/5f/Minecraft_%E2%80%93_Volume_Alpha.jpeg",
      streams: "3.4B",
    },
    {
        id: 3,
        title: "Drake",
        description: "Dark Drake as I like to call this album",
        album: "Dark Lane Demo Tapes",
        image: "https://upload.wikimedia.org/wikipedia/en/6/6b/Drake_-_Dark_Lane_Demo_Tapes.png",
        streams: "1.89B",
      },
      {
        id: 4,
        title: "Joji",
        description: "2AM out for a drive",
        album: "Nectar",
        image: "https://upload.wikimedia.org/wikipedia/en/1/1b/Joji_-_Nectar.png",
        streams: "2.3B",
      },
      {
        id: 5,
        title: "Frank Ocean",
        description: "walking in the city on a cloudy evening",
        album: "Blonde",
        image: "https://upload.wikimedia.org/wikipedia/en/a/a0/Blonde_-_Frank_Ocean.jpeg",
        streams: "800M",
      },
      {
        id: 6,
        title: "Fred Again",
        description: "riding the bus at night while its raining",
        album: "Actual Life 3",
        image: "https://www.fredagain.com/assets/img/albumArt.png",
        streams: "45M",
      },
      {
        id: 7,
        title: "Kaytranada",
        description: "dance",
        album: "Boiler Room Set",
        image: "https://boilerroom.tv/cdn-cgi/image/width=1312,height=1312,fit=cover,format=auto/https://stash-archive-master-videos.s3.amazonaws.com/assets/Screen_Shot_2018-05-15_at_14.23.28.jpg",
        streams: "16M",
      },
      {
        id: 8,
        title: "21 Savage",
        description: "gym tunes",
        album: "Without Warning",
        image: "https://upload.wikimedia.org/wikipedia/en/d/de/21_Savage%2C_Offset_%26_Metro_Boomin_-_Without_Warning.png",
        streams: "650M",
      },
      {
        id: 9,
        title: "NAV",
        description: "chilling with the boys",
        album: "Perfect Timing",
        image: "https://images.genius.com/0bcd2c5abeb1e5899efc06b7e872d07f.1000x1000x1.png",
        streams: "300M",
      },
      {
        id: 10,
        title: "88GLAM",
        description: "racing on the highway",
        album: "88GLAM RELOADED",
        image: "https://i.discogs.com/jvBLcWVy5uUQ8LpZWH6hWFx01sQ2q0qnstcHUuymhLU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExNzQ3/NTU0LTE1MjE2OTY2/MjgtNzk4Ny5qcGVn.jpeg",
        streams: "25M",
      },
  ];
  